PrivateKey = {Path = "/etc/cdk/dac.keystore", Password = "test"}

[L1]
WsURL = "wss://eth-sepolia.g.alchemy.com/v2/???????????????"
RpcURL = "https://eth-sepolia.g.alchemy.com/v2/????????????????????"
PolygonValidiumAddress = "????????" #POE/ZKEVM ADDR
DataCommitteeAddress = "??????"
Timeout = "1m"
RetryPeriod = "5s"
BlockBatchSize = "64"
GenesisBlock = "0"
TrackSequencer = false

[Log]
Environment = "development" # "production" or "development"
Level = "info"
Outputs = ["stderr"]

[DB]
User = "dac_user"
Password = "dac_password"
Name = "dac_db"
Host = "cdk-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = 8484
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
