IsTrustedSequencer = true

[Log]
Environment = "development" # "production" or "development"
Level = "info"
Outputs = ["stderr"]

[State]
	[State.DB]
	User = "state_user"
	Password = "state_password"
	Name = "state_db"
	Host = "zkevm-db"
	Port = "5432"
	EnableLog = false	
	MaxConns = 200
	[State.Batch]
		[State.Batch.Constraints]
		MaxTxsPerBatch = 300
		MaxBatchBytesSize = 120000
		MaxCumulativeGasUsed = 30000000
		MaxKeccakHashes = 2145
		MaxPoseidonHashes = 252357
		MaxPoseidonPaddings = 135191
		MaxMemAligns = 236585
		MaxArithmetics = 236585
		MaxBinaries = 473170
		MaxSteps = 7570538
		MaxSHA256Hashes = 1596

[Pool]
MaxTxBytesSize = 100132
MaxTxDataBytesSize = 100000
DefaultMinGasPriceAllowed = 1000000000
MinAllowedGasPriceInterval = "5m"
PollMinAllowedGasPriceInterval = "1s"
IntervalToRefreshBlockedAddresses = "5m"
IntervalToRefreshGasPrices = "5s"
AccountQueue = 0
GlobalQueue = 0
	[Pool.DB]
		User = "pool_user"
		Password = "pool_password"
		Name = "pool_db"
		Host = "zkevm-db"
		Port = "5432"
		EnableLog = false
		MaxConns = 200
	[Pool.EffectiveGasPrice]
		Enabled = true
		L1GasPriceFactor = 0.04
		ByteGasCost = 16
		ZeroByteGasCost = 4
		NetProfit = 1.2
	        BreakEvenFactor = 1.3
		FinalDeviationPct = 10
		L2GasPriceSuggesterFactor = 0.30

[Etherman]
URL = "foo"
ForkIDChunkSize = 20000
MultiGasProvider = false
	[Etherscan]
		ApiKey = ""

[RPC]
Host = "0.0.0.0"
Port = 8123
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 3000
EnableHttpLog = false
MaxNativeBlockHashBlockRange = 60000
BatchRequestsEnabled = true
BatchRequestsLimit = 20
MaxLogsCount = 10000
MaxLogsBlockRange = 10000
SequencerNodeURI = ""
	[RPC.WebSockets]
		Enabled = true
		Port = 8546
		ReadLimit = 104857600

[Synchronizer]
SyncInterval = "5s"
SyncChunkSize = 100
TrustedSequencerURL = ""
L1SynchronizationMode = "sequential"
	[Synchronizer.L1ParallelSynchronization]
		MaxClients = 10
		MaxPendingNoProcessedBlocks = 25
		RequestLastBlockPeriod = "5s"
		RequestLastBlockTimeout = "5s"
		RequestLastBlockMaxRetries = 3
		StatisticsPeriod = "5m"
		TimeoutMainLoop = "5m"
		RollupInfoRetriesSpacing= "5s"
		FallbackToSequentialModeOnSynchronized = false
		[Synchronizer.L1ParallelSynchronization.PerformanceWarning]
			AceptableInacctivityTime = "5s"
			ApplyAfterNumRollupReceived = 10

[Sequencer]
DeletePoolTxsL1BlockConfirmations = 100
DeletePoolTxsCheckInterval = "12h"
TxLifetimeCheckInterval = "10m"
TxLifetimeMax = "3h"
LoadPoolTxsCheckInterval = "500ms"
StateConsistencyCheckInterval = "5s"
	[Sequencer.Finalizer]
		NewTxsWaitInterval = "100ms"
		ForcedBatchesTimeout = "60s"
		ForcedBatchesL1BlockConfirmations = 60
		ForcedBatchesCheckInterval = "30s"
		L1InfoTreeL1BlockConfirmations = 60
		L1InfoTreeCheckInterval = "30s"
		BatchMaxDeltaTimestamp = "600s"
		L2BlockMaxDeltaTimestamp = "3s"		
		ResourceExhaustedMarginPct = 10
		HaltOnBatchNumber = 0
		SequentialBatchSanityCheck = false		
	[Sequencer.StreamServer]
		Port = 6900
		Filename = "/datastreamer/datastream.bin"
		Enabled = true

[SequenceSender]
WaitPeriodSendSequence = "60s"
LastBatchVirtualizationTimeMaxWaitPeriod = "600s"
MaxTxSizeForL1 = 131072
GasOffset = 80000
L2Coinbase = "foo"
PrivateKey = {Path = "/app/sequencer.keystore", Password = "test"}

[Aggregator]
Host = "0.0.0.0"
Port = 50081
RetryTime = "5s"
VerifyProofInterval = "25m"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1.1"
ProofStatePollingInterval = "5s"
SenderAddress = "foo"
CleanupLockedProofsInterval = "2m"
GeneratingProofCleanupThreshold = "15m"
GasOffset = 0

[EthTxManager]
GasPriceMarginFactor = 1
MaxGasPriceLimit = 0
FrequencyToMonitorTxs = "1s"
WaitTxToBeMined = "2m"
ForcedGas = 0
PrivateKeys = [
	{Path = "/app/sequencer.keystore", Password = "test"},
	{Path = "/app/aggregator.keystore", Password = "test"}
]

[L2GasPriceSuggester]
Type = "follower"
UpdatePeriod = "10s"
Factor = 0.25
DefaultGasPriceWei = 100000000
MaxGasPriceWei = 0
CleanHistoryPeriod = "1h"
CleanHistoryTimeRetention = "5m"

[MTClient]
URI  = "zkevm-executor:50061"

[Executor]
URI = "zkevm-executor:50071"
MaxGRPCMessageSize = 100000000
MaxResourceExhaustedAttempts = 3
WaitOnResourceExhaustion = "1s"

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = true

[EventLog]
	[EventLog.DB]
	User = "events_user"
	Password = "events_password"
	Name = "events_db"
	Host = "zkevm-db"
	Port = "5432"
	EnableLog = false
	MaxConns = 200

[HashDB]
User = "hash_user"
Password = "hash_password"
Name = "hash_db"
Host = "zkevm-db"
Port = "5432"
EnableLog = false
MaxConns = 200
